# Tasks to install java8 in /opt

---

- name: Check presence of jdk release
  command: ls -ald /opt/jdk{{jdkversion}}_{{jdkpatch}}
  register: jdkpresent
  ignore_errors: yes
  always_run: yes

- name: Download JDK
  command: creates=/tmp/jdk.tgz curl -o /tmp/jdk.tgz --cookie "oraclelicense=accept-securebackup-cookie" -L http://download.oracle.com/otn-pub/java/jdk/{{javaversion}}u{{jdkpatch}}-b{{jdkbuild}}/server-jre-{{javaversion}}u{{jdkpatch}}-linux-x64.tar.gz
  when: "'No such file or directory' in jdkpresent.stderr"

- name: Extract JDK release
  shell: tar -C /opt -zxvf /tmp/jdk.tgz creates=/opt/jdk{{jdkversion}}_{{jdkpatch}}
  when: "'No such file or directory' in jdkpresent.stderr"

- name: Remove jdk tarball
  command: rm /tmp/jdk.tgz
  when: "'No such file or directory' in jdkpresent.stderr"

- name: Create java8 symlink
  file: src=/opt/jdk{{jdkversion}}_{{jdkpatch}} dest=/opt/java8 owner=root group=root state=link

- name: java profile settings
  copy: src=javaprofile.sh dest=/etc/profile.d/java.sh owner=root group=root mode=0755
